### ISSUE TITLE
EffectFallbacks class file has moved

### ISSUE THREAD

**Issue by itubiaoge** [virtual-cast/babylon-mtoon-material#41]
I use mtoon by npm, run code with error:s.EffectFallbacks is not constructor. I found effectFallbacks method is in '@babylonjs/core/Materials/effectFallbacks', but it is not required by mtoon.

**Comment by il-m-yamagishi** [comment]
From Babylon.js 4.1.0-alpha.21, class EffectFallbacks moves from effect.ts to effectFallbacks.ts.

Ref. https://github.com/BabylonJS/Babylon.js/commit/6282bff7d3f6687ad47bd56cfbc609859c2ad5b7#diff-b322e3fcece526862666ff993e092ca0

I will try to fix it, otherwise you can use 4.1.0-alpha.20 or older.

**Comment by itubiaoge** [comment]
@il-m-yamagishi thank you!
